version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app/server
    command: ["npm", "start"]

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
    command: ["npm", "start"]