export const GET_EXPENSES_BEGIN = 'GET_EXPENSES_BEGIN';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CREATE_EXPENSES_BEGIN = 'CREATE_EXPENSES_BEGIN';
export const CREATE_EXPENSES_SUCCESS = 'CREATE_EXPENSES_SUCCESS';
export const CREATE_EXPENSES_ERROR = 'CREATE_EXPENSES_ERROR';
export const DELETE_EXPENSES_BEGIN = 'DELETE_EXPENSES_BEGIN';

export const SET_EDIT_EXPENSES = 'SET_EDIT_EXPENSES';


export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const UPDATE_EXPENSES_BEGIN = 'UPDATE_EXPENSES_BEGIN';
export const UPDATE_EXPENSES_SUCCESS = 'UPDATE_EXPENSES_SUCCESS';
export const UPDATE_EXPENSES_ERROR = 'UPDATE_EXPENSES_ERROR';