export const GET_EXPENSES_BEGIN = 'GET_EXPENSES_BEGIN';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';

export const CREATE_EXPENSES_BEGIN = 'CREATE_EXPENSES_BEGIN';
export const CREATE_EXPENSES_SUCCESS = 'CREATE_EXPENSES_SUCCESS';
export const CREATE_EXPENSES_ERROR = 'CREATE_EXPENSES_ERROR';
export const DELETE_EXPENSES_BEGIN = 'DELETE_EXPENSES_BEGIN';


export const TOGGLE_MODAL = 'TOGGLE_MODAL';